Adding gunicorn custom config file and code profiler dependencies
Azure-App-Service/ImageBuilder pull request #149
Opened 2021-11-30 05:18 UTC by vijaysaayi

This PR introduces
1. A Custom gunicorn config file
2. Installs the code profiler for Python versions >3.6 using gunicorn config
3. Creates a PID file through gunicorn config that is needed for profiler

2021-12-02 18:08 UTC, purva-vasudeo commented on GenerateDockerFiles/python/template-3.9/gunicorn.conf.py
> +import constants
Would this file be overwriting the default one provided by Oryx? If so, what is the impact on existing customers using the default config?

2021-12-02 18:11 UTC, vijaysaayi commented on GenerateDockerFiles/python/template-3.7/Dockerfile
> +ENV PYTHON_USE_GUNICORN_CONFIG_FROM_PATH "/opt/startup/gunicorn.conf.py"
This environment variable tells Oryx to pick the config from this path. 
If this env doesnt exist then Oryx will not use Custom Gunicorn config.

To enable code profiler, Customer has to use a different App Setting WEBSITE_ENABLE_DEFAULT_CODE_PROFILER

2021-12-02 18:16 UTC, vijaysaayi commented on GenerateDockerFiles/python/template-3.9/gunicorn.conf.py
> +import constants
This file adds only two extra config:
1. A file which stores the PID of the gunicorn worker process. This is needed because gunicorn uses pre-forker worker model. So if Customer runs px -ax, there will be extra gunicorn process. If there is a file that has the pid, it will be easy for Customer to attach code-profiler to the right python process.
2. Add signal handler when ENABLE_CODE_PROFILER app setting is present.

Oryx today take only one input which requests for multiple workers. This behavior remains unchanged as in startup script Oryx add -w <number of workers>.

2021-12-02 19:12 UTC, purva-vasudeo commented on GenerateDockerFiles/python/template-3.7/Dockerfile
> +ENV PYTHON_USE_GUNICORN_CONFIG_FROM_PATH "/opt/startup/gunicorn.conf.py"
So then shouldn't this env only be set when customer enables WEBSITE_ENABLE_DEFAULT_CODE_PROFILER?

2021-12-03 04:35 UTC, vijaysaayi commented on GenerateDockerFiles/python/template-3.7/Dockerfile
> +ENV PYTHON_USE_GUNICORN_CONFIG_FROM_PATH "/opt/startup/gunicorn.conf.py"
@purva-vasudeo : The Custom config for gunicorn helps in brining support for various diagnostic tools for Python App Services.
Hence we use PYTHON_USE_GUNICORN_CONFIG_FROM_PATH to request Oryx to pickup the config from the specific path. 

WEBSITE_ENABLE_DEFAULT_CODE_PROFILER is specifically for enabling code profiler.
For example, memory dump tool can have its own App Setting.

2021-12-03 18:25 UTC, purva-vasudeo approved these changes

2021-12-06 05:16 UTC, kumaramit-msft requested changes

2021-12-06 05:16 UTC, kumaramit-msft commented on GenerateDockerFiles/python/template-3.7/gunicorn.conf.py
> +Path(constants.CODE_PROFILER_LOGS_DIR).mkdir(parents=True, exist_ok=True)
This line will run, even if the module is loaded and may run into exception if unable to create a dir. Better to keep it under a try block.

2021-12-06 05:16 UTC, kumaramit-msft commented on GenerateDockerFiles/python/template-3.9/gunicorn.conf.py
> +import code_profiler_installer as c
Better to import it as maybe some name as cpi, so that code is easy to read.

2021-12-06 05:16 UTC, kumaramit-msft commented on GenerateDockerFiles/python/common/code_profiler/code_profiler_installer.py
> +import constants as c
c is also used to code_profiler_installer, you can import constants as `consts`.

2021-12-06 05:16 UTC, kumaramit-msft commented on GenerateDockerFiles/python/common/code_profiler/code_profiler_installer.py
> +import os
Keep import in sorted order and follow a coherent order for different import styles:

import yyyy

import zzzz as z

from x import y

2021-12-06 05:16 UTC, kumaramit-msft commented on GenerateDockerFiles/python/common/code_profiler/code_profiler_installer.py
> +        return enable_profiler_appsetting_value is not None \
Try not to use \ as it may end up including next line if unchecked (happens when sometimes we edit/delete lines). Better to use (), as it can span across multiple-lines and gives syntax error than having a runtime error.

2021-12-06 06:51 UTC, vijaysaayi commented on GenerateDockerFiles/python/common/code_profiler/code_profiler_installer.py
> +import os
Updated the suggestion

2021-12-06 06:51 UTC, vijaysaayi commented on GenerateDockerFiles/python/common/code_profiler/code_profiler_installer.py
> +        return enable_profiler_appsetting_value is not None \
Updated the suggestion

2021-12-06 06:58 UTC, vijaysaayi commented on GenerateDockerFiles/python/template-3.9/gunicorn.conf.py
> +import code_profiler_installer as c
Updated the suggestion.

2021-12-06 06:58 UTC, vijaysaayi commented on GenerateDockerFiles/python/common/code_profiler/code_profiler_installer.py
> +import constants as c
Updated the suggestion.

2021-12-06 07:11 UTC, vijaysaayi commented on GenerateDockerFiles/python/template-3.7/gunicorn.conf.py
> +Path(constants.CODE_PROFILER_LOGS_DIR).mkdir(parents=True, exist_ok=True)
Updated the suggestion.

2021-12-06 15:04 UTC, kumaramit-msft approved these changes

2021-12-07 05:24 UTC, merged